### ISSUE TITLE
`safety.check` generate error

### ISSUE THREAD

**Issue by natir** [pawamoy/duty#14]
**Describe the bug**
Calling `safety.check` generate error on importlib.invalidate_caches.

Code: 
```python
    requirements = ctx.run(
        ["pdm", "export", "-f", "requirements", "--without-hashes"],
        title="Exporting dependencies as requirements",
        allow_overrides=False,
    )

    ctx.run(
        safety.check(requirements),
        title="Checking dependencies",
        command="pdm export -f requirements --without-hashes | safety check --stdin",
    )
```

Error:
```
  Traceback (most recent call last):
    File "__pypackages__/3.11/lib/failprint/runners.py", line 223, in run_function_get_code
      result = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
    File "__pypackages__/3.11/lib/failprint/lazy.py", line 37, in __call__
      return self.call(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "__pypackages__/3.11/lib/duty/callables/safety.py", line 43, in check
      importlib.invalidate_caches()
    File "/usr/lib64/python3.11/importlib/__init__.py", line 70, in invalidate_caches
      finder.invalidate_caches()
  TypeError: MetaPathFinder.invalidate_caches() missing 1 required positional argument: 'self'
```

**System (please complete the following information):**
- `duty` version: 1.0.0
- Python version: 3.9
- OS: Linux

**Comment by pawamoy** [comment]
Waiting for a release of the `editables` package, see https://github.com/pfmoore/editables/issues/31 :slightly_smiling_face: 
@pfmoore could you publish a new version?

**Comment by pfmoore** [comment]
Done

**Comment by pawamoy** [comment]
Thanks!
