### ISSUE TITLE
bug: The `blacken_docs` API has been updated

### ISSUE THREAD

**Issue by jexio** [pawamoy/duty#22]
### Description of the bug

TypeError: format_file() missing 1 required positional argument: 'check_only'

### To Reproduce
```
blacken_docs.run(*PY_SRC_LIST, "docs", exts=["py", "md"], ...)
```

Traceback (most recent call last):
```
    File "/home/user/.cache/pypoetry/virtualenvs/irv-logging-SL_A2R03-py3.12/lib/python3.12/site-packages/failprint/runners.py", line 214, in run_function_get_code
      result = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
    File "/home/user/.cache/pypoetry/virtualenvs/irv-logging-SL_A2R03-py3.12/lib/python3.12/site-packages/failprint/lazy.py", line 37, in __call__
      return self.call(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/user/.cache/pypoetry/virtualenvs/irv-logging-SL_A2R03-py3.12/lib/python3.12/site-packages/duty/callables/blacken_docs.py", line 78, in run
      retv |= format_file(
              ^^^^^^^^^^^^
  TypeError: format_file() missing 1 required positional argument: 'check_only'
```

</details>

### Environment information

- __System__: Linux-6.8.0-40-generic-x86_64-with-glibc2.35
- __Python__: cpython 3.12.5 (/home/user/.cache/pypoetry/virtualenvs/irv-logging-SL_A2R03-py3.12/bin/python)
- __Environment variables__:
- __Installed packages__:
  - `duty` v1.4.1

### Additional context

blacken_docs == 1.18.0

**Comment by pawamoy** [comment]
Thanks for the report, fixed in 1.4.2 :slightly_smiling_face:
